
    create table ICLICKER_LOCK (
        ID bigint generated by default as identity (start with 1),
        LAST_MODIFIED timestamp not null,
        NAME varchar(255) not null,
        HOLDER varchar(255) not null,
        primary key (ID),
        unique (NAME)
    );

    create table ICLICKER_REGISTRATION (
        id bigint generated by default as identity (start with 1),
        clickerId varchar(16) not null,
        ownerId varchar(255) not null,
        locationId varchar(255),
        activated bit not null,
        national bit not null,
        dateCreated timestamp not null,
        dateModified timestamp not null,
        primary key (id)
    );

    create table ICLICKER_USER_KEY (
        ID bigint generated by default as identity (start with 1),
        USER_ID varchar(255) not null,
        USER_KEY varchar(255) not null,
        dateCreated timestamp not null,
        dateModified timestamp not null,
        primary key (ID),
        unique (USER_ID)
    );

    create index clicker_lock_name on ICLICKER_LOCK (NAME);

    create index clicker_user_key on ICLICKER_USER_KEY (USER_KEY);

    create index clicker_user_id on ICLICKER_USER_KEY (USER_ID);
